[package]
name = "keysafe_serveur"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pwhash = "1"
machine = "0.3.0"
serde_json = "1.0.59"
serde = "1.0.117"
serde_derive = "1.0.117"